title: 小王子的治愈世界
description: 个人治愈系博客
baseurl: ""
url: "https://yourusername.github.io"
theme: jekyll-theme-minimal

plugins:
  - jekyll-feed

exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - README.md